captions:
- Free! # don't change
- Donra is flamed
- Tank dies last
- Hunter didn't do mechanics
- Woody reexplains the whole fight
- Hunters pull extra ads
- Wipe on ads
- Someone isn't on time
- Charles titanforges
- Someone dies to dodgeable lasers two pulls in a row
- Someone dies of containment chamber fire
- Last minute flaker
- A DPS is flamed for not switching to ads
- One hour in: “OH LOL I FORGOT TO FLASK”
- Someone dies to frontal cone
- Pool is placed in VERY BAD LOCATION
- Boss is accidentally pulled
- Missed dispel
- Woody has to re-explain entire fight
- Lust is used at completely the wrong time
- Delays because someone forgot to turn off war mode
- Woody has orange parses
- Kick rotation is out of order
- Missing consumables
- Pulled incorectly timer
- Release after "Do not release" is called
