captions:
# General
- Free! # don't change
- Someone isn't on time
- Last minute flaker
- Donra is flamed
- Tank dies last
- Hunter didn't do mechanics
- Woody reexplains the whole fight
- Hunters pull extra ads
- Wipe on ads
- A DPS is flamed for not switching to ads
- Boss is accidentally pulled
- Charles titanforges
- Missed dispel
- One hour in: “OH LOL I FORGOT TO FLASK”
- Someone dies to frontal cone
- Lust is used at completely the wrong time
- Woody has orange parses
- Kick rotation is out of order
- Missing consumables
- Pulled incorectly timer
- Release after "Do not release" is called
# - Delays because someone forgot to turn off war mode # Not really applicable for this one

# Raid Specific
- Someone dies to dodgeable lasers two pulls in a row
- Someone dies of containment chamber fire
- Pool is placed in VERY BAD LOCATION
