captions:
- Free! # don't change
- Tank died (impossible)
- Hunter didn't do mechanics
- Woody reexplains the whole fight
- Hunters pull extra ads
- Wipe on ads
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
- Someone isn't on time
