captions:
# General
- Free! # don't change
- Someone isn't on time
- Last minute flaker
- Tank dies last
- Hunter didn't do mechanics
- Hunters pull extra ads
- Wipe on ads
- A melee DPS is flamed for not switching to ads
- East Coaster(s) ignore mechanic for dps increase
- Boss is accidentally pulled
- Missed dispel
- 'One hour in: “OH LOL I FORGOT TO FLASK”'
- Someone dies to frontal cone
- Lust is used at completely the wrong time
- Kick rotation is out of order
- Missing consumables
- 'Wait I need food buff, don't pull'
- Pulled incorrectly timer
- Release after "Do not release" is called
- Lazy POS asks for summons
- Cauldron dropped after personal flask(s) used
- Multiple feasts for hungry raiders
- Too many chefs in the kitchen
- PUGs ended raid night
- All 12 classes present in raid
- An old guildie returns to raid
- BoE drops
# - Delays because someone forgot to turn off war mode # Not really applicable for this one

# Raid Specific
- "My corruption gear isn't the problem"
- T-Boned
- Cataclysm kills someone
- Someone knocked off
- Mount running off the ledge
- Jumps into gapping hole and dies
- Death by DPS reflection
- One shot by Stygian Annihilation
- Failed to score
- "GOAL!"
- Death by soccer ball
- Someone trampled to death
- '"The boss was at 1 health" and wiped'
- Overrun by boss adds
- Roly-polyed
- Tank gave the dog water
- Elevator death
- VITA strikes entire raid
- Unstable void missle not soaked
- Death by Twilight Decimator
- Tentacle slammed
- Carapace eyeball kicked
- Death by Paranoia
- Nzoth MCs someone

# People Specific
- Pinecone got charmed
- Pinecone complains about buffs
- Donra is flamed
- Bone soup pun
- Bee fact
- Jason swearing
- Bar is top DPS
- Tank flames Bar
- 'Which Andy?'
- Sunny D
- Dick shen orange parses
- 'Can I ams this'
- Woody compliments raid
