captions:
# General
- Free! # don't change
- Someone isn't on time
- Last minute flaker
- Donra is flamed
- Tank dies last
- Hunter didn't do mechanics
- Woody reexplains the whole fight
- Hunters pull extra ads
- Wipe on ads
- A melee DPS is flamed for not switching to ads
- Boss is accidentally pulled
- Charles titanforges
- Missed dispel
- 'One hour in: “OH LOL I FORGOT TO FLASK”'
- Someone dies to frontal cone
- Lust is used at completely the wrong time
- Woody has orange parses
- Kick rotation is out of order
- Missing consumables
- Bone soup pun
- Pulled incorrectly timer
- Release after "Do not release" is called
- Lazy POS asks for summons
- Multiple feasts for hungry raiders
- Too many chefs in the kitchen
- PUGs ended raid night
# - Delays because someone forgot to turn off war mode # Not really applicable for this one

# Raid Specific
- "My corruption gear isn't the problem"
- T-Boned
- Cataclysm kills someone 
- Someone knocked off
- Death by DPS reflection
- Failed to score
- "GOAL!"
- Death by soccer ball
- Someone trampled to death
- Someone '/spit's on Azshara
- "The boss was at 1 health" and wiped
- Roly-polyed
- Tank gave the dog water
- Pinecone got charmed
- VITA strikes entire raid
