captions:
# General
- Free! # don't change
- Someone isn't on time
- Last minute flaker
- Donra is flamed
- Tank dies last
- Hunter didn't do mechanics
- Woody reexplains the whole fight
- Hunters pull extra ads
- Wipe on ads
- A DPS is flamed for not switching to ads
- Boss is accidentally pulled
- Charles titanforges
- Missed dispel
- One hour in: “OH LOL I FORGOT TO FLASK”
- Someone dies to frontal cone
- Lust is used at completely the wrong time
- Woody has orange parses
- Kick rotation is out of order
- Missing consumables
- Pulled incorectly timer
- Release after "Do not release" is called
- Lazy POS asks for summons
- Multiple feasts for hungry raiders
# - Delays because someone forgot to turn off war mode # Not really applicable for this one

# Raid Specific
- Someone dies to dodgeable lasers two pulls in a row
- Someone dies of containment chamber fire
- Pool is placed in VERY BAD LOCATION
- Failed to play Simon
- Scared to death by a monkey
- Punished by flames
- Blissfully unaware laser target
- Spilled liquid gold all over the raid
- Executed for gem thievery
- Raid mauled by a tiger
- Death by no-stabby honor
- Ended, inevitably
- Wiped to Touhou boss
- Honey, I shrunk the raid (and killed them)
- Buster Cannon to the face
- Raid electrocuted
- Drowned in the ocean
- Victim of the siren's song
- Energized Storm doesn't know personal space
- Icefall, everyone blocked
- Ballistae burn forever
- Huddled for warmth around the Heart of Frost
- Indestructible barrels
- Ice Beam inflicts FRZ
