name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

      - name: Build Docker image
        run: docker build -t docker.pkg.github.com/sheldonkwok/wow-bingo/wow-bingo .
      - name: Github pkg login
        run: echo $GITHUB_TOKEN | docker login --username sheldonkwok --password-stdin docker.pkg.github.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Docker image
        run: docker push docker.pkg.github.com/sheldonkwok/wow-bingo/wow-bingo
